name: Android CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: 'AndroidCookbook'
          sparse-checkout-cone-mode: false

      - name: Move mobile app files to root
        run: |
          ls -lah
          shopt -s dotglob
          mv AndroidCookbook/* .
          rm -rf AndroidCookbook
          ls -lah

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            8
            11
            21
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: |
          ./gradlew assemble
  
  unit-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: 'AndroidCookbook'
          sparse-checkout-cone-mode: false

      - name: Move mobile app files to root
        run: |
          ls -lah
          shopt -s dotglob
          mv AndroidCookbook/* .
          rm -rf AndroidCookbook
          ls -lah

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            8
            11
            21
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: |
          ./gradlew test

  ui-testing:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        api-level: [ 26, 29, 31, 34 ]
    steps:

      - uses: actions/checkout@v4
        with:
          sparse-checkout: 'AndroidCookbook'
          sparse-checkout-cone-mode: false

      - name: Move mobile app files to root
        run: |
          ls -lah
          shopt -s dotglob
          mv AndroidCookbook/* .
          rm -rf AndroidCookbook
          ls -lah

      - name: Load Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: |
            8
            11
            21
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble tests
        run: ./gradlew build assembleAndroidTest

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
            ~/.android/debug.keystore
          key: avd-${{ matrix.api-level }}

      - name: Run emulator to generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: ./
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: Galaxy Nexus
          cores: 2
          sdcard-path-or-size: 100M
          avd-name: test
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          working-directory: ./test-fixture/
          channel: canary
          script: echo "Generated AVD snapshot for caching."

      - name: Run UI Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: aosp_atd
          arch: x86_64
          profile: Galaxy Nexus
          cores: 2
          ram-size: 2048M
          sdcard-path-or-size: 100M
          avd-name: test
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          channel: canary
          pre-emulator-launch-script: |
            echo "Running pre emulator launch script. Printing the working directory now:"
            pwd
          script: |
            echo $GITHUB_REPOSITORY
            adb devices
            ./gradlew connectedDebugAndroidTest


