name: Android CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: 'AndroidCookbook'
          sparse-checkout-cone-mode: false

      - name: Move mobile app files to root
        run: |
          ls -lah
          shopt -s dotglob
          mv AndroidCookbook/* .
          rm -rf AndroidCookbook
          ls -lah

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            8
            11
            21
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: |
          ./gradlew clean testDebug

  ui-testing:
    runs-on: macos-10.15
    strategy:
      matrix:
        api-level: [26, 28, 31]
        target: [default, google_apis]
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: 'AndroidCookbook'
          sparse-checkout-cone-mode: false

      - name: Move mobile app files to root
        run: |
          ls -lah
          shopt -s dotglob
          mv AndroidCookbook/* .
          rm -rf AndroidCookbook
          ls -lah

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: |
            8
            11
            21
          cache: 'gradle'

      - name: Run UI Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          script: ./gradlew connectedCheck --no-daemon --stacktrace


